# Generated by Django 4.2.7 on 2023-11-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_catalog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalog',
            table=None,
        ),
    ]
