# Generated by Django 4.2.7 on 2023-11-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
